fix(network-checks): Fix tokio panic by using hickory’s `TokioAsyncResolver`
I can’t get a useful stacktrace but I think `spawn_blocking` caused:

```log
thread 'tokio-runtime-worker' panicked at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.43.0/src/runtime/blocking/shutdown.rs:51:21:
Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.
```

<https://users.rust-lang.org/t/tonic-tokio-cannot-drop-a-runtime-in-a-context-where-blocking-is-not-allowed/116667/3> would support that.