fix(ci): Setup QEMU and Docker Buildx before building the Docker image to support multi-platform builds
Without it, we'd get

```log
ERROR: Multi-platform build is not supported for the docker driver.
Switch to a different driver, or turn on the containerd image store, and try again.
Learn more at https://docs.docker.com/go/build-multi-platform/
```

See https://github.com/docker/build-push-action?tab=readme-ov-file#usage.